// bake.js — bakes intro.md into intro.baked.js before publishing.
//
// The site is a dependency-free static page, so it must NOT parse markdown at
// runtime. This script converts intro.md into a JS module that exports the
// pre-rendered HTML string. Run it whenever intro.md changes:
//
//   node bake.js
//
// and commit the generated intro.baked.js alongside your edit.

const fs = require("fs");
const path = require("path");

const SRC = path.join(__dirname, "intro.md");
const OUT = path.join(__dirname, "intro.baked.js");

// --- Minimal, self-contained markdown -> HTML (no dependencies) -------------
// Supports the subset used by intro.md: ATX headings, paragraphs, unordered
// and ordered lists, hard line breaks (two trailing spaces), and the inline
// spans **bold**, *italic*/_italic_, `code`, and [text](url).

function escapeHtml(s) {
  return s.replace(/&/g, "&amp;").replace(/</g, "&lt;").replace(/>/g, "&gt;");
}

function inline(text) {
  let out = escapeHtml(text);
  out = out.replace(/`([^`]+)`/g, (_, c) => `<code>${c}</code>`);
  out = out.replace(
    /\[([^\]]+)\]\(([^)]+)\)/g,
    (_, t, u) => `<a href="${escapeHtml(u)}">${t}</a>`,
  );
  out = out.replace(/\*\*([^*]+)\*\*/g, "<strong>$1</strong>");
  out = out.replace(/\*([^*]+)\*/g, "<em>$1</em>");
  out = out.replace(/_([^_]+)_/g, "<em>$1</em>");
  return out;
}

function mdToHtml(md) {
  const lines = md.replace(/\r\n/g, "\n").split("\n");
  const blocks = [];
  let para = [];

  function flushPara() {
    if (!para.length) return;
    let html = "";
    for (let k = 0; k < para.length; k++) {
      const hard = / {2,}$/.test(para[k]); // two trailing spaces = hard break
      html += inline(para[k].replace(/\s+$/, ""));
      if (k < para.length - 1) html += hard ? "<br>\n" : " ";
    }
    blocks.push(`<p>${html}</p>`);
    para = [];
  }

  function takeList(i, itemRe, tag) {
    const items = [];
    while (i < lines.length && itemRe.test(lines[i].trim())) {
      items.push(`<li>${inline(lines[i].trim().replace(itemRe, ""))}</li>`);
      i++;
    }
    blocks.push(`<${tag}>\n${items.join("\n")}\n</${tag}>`);
    return i - 1; // caller's loop will ++ past the last consumed line
  }

  for (let i = 0; i < lines.length; i++) {
    const trimmed = lines[i].trim();

    if (trimmed === "") {
      flushPara();
      continue;
    }

    const heading = /^(#{1,6})\s+(.*)$/.exec(trimmed);
    if (heading) {
      flushPara();
      const level = heading[1].length;
      blocks.push(`<h${level}>${inline(heading[2].trim())}</h${level}>`);
      continue;
    }

    if (/^[-*+]\s+/.test(trimmed)) {
      flushPara();
      i = takeList(i, /^[-*+]\s+/, "ul");
      continue;
    }

    if (/^\d+\.\s+/.test(trimmed)) {
      flushPara();
      i = takeList(i, /^\d+\.\s+/, "ol");
      continue;
    }

    para.push(lines[i]);
  }
  flushPara();
  return blocks.join("\n");
}

const md = fs.readFileSync(SRC, "utf8");
const html = mdToHtml(md);
const banner =
  "// GENERATED by bake.js from intro.md — do not edit by hand.\n" +
  "// Run `node bake.js` to regenerate.\n";
fs.writeFileSync(OUT, `${banner}export const introHtml = ${JSON.stringify(html)};\n`);
console.log(`Baked ${path.basename(SRC)} -> ${path.basename(OUT)} (${html.length} chars)`);
